name: Lint

on:
  push:
    branches:
      - main  # Run linting when making changes to main
  pull_request:
    branches:
      - main  # Run linting when making pull request to main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Choose the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy isort

    - name: Run Flake8
      run: |
        flake8 .  # This will check all .py files in the current directory and its subdirectories

    - name: Run MyPy
      run: |
        mypy --ignore-missing-imports .  # Ignore missing imports during MyPy check

    - name: Run isort and auto-fix imports
      run: |
        isort --atomic .  # Automatically fix imports using isort

    - name: commit isort changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A && git diff-index --cached --quiet HEAD || git commit -m 'isort'

    - name: push isort changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

