name: Lint

on:
  push:
    branches:
      - main  # Update this to your main branch name
  pull_request:
    branches:
      - main  # Update this to your main branch name

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Choose the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run Flake8
      run: |
        flake8 .  # This will check all .py files in the current directory and its subdirectories
