name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy isort python-dotenv pytest openai==0.28.0

      - name: Set up environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Run Flake8
        run: |
          flake8 .  # This will check all .py files in the current directory and its subdirectories

      - name: Run MyPy
        run: |
          mypy --ignore-missing-imports .  # Ignore missing imports during MyPy check

      - name: Run isort
        run: |
          isort --check-only --diff .  # This will check and show changes made by isort

      - name: Run smoke tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

        run: |
          cd tests/smoke_tests
          pytest test_smoke.py

      - name: Run Unit tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

        run: |
          cd tests/unit_tests
          pytest test_gpt_prompts.py
