name: Main Workflow

on:
  push:
    branches:
      - main  # Run linting when making changes to main
  pull_request:
    branches:
      - main  # Run linting when making pull request to main
      -
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy isort os python-dotenv pytest

      - name: Set up environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: Run Flake8
        run: |
          flake8 .  # This will check all .py files in the current directory and its subdirectories

      - name: Run MyPy
        run: |
          mypy --ignore-missing-imports .  # Ignore missing imports during MyPy check

      - name: Run isort and auto-fix imports
        run: |
          isort --check-only --diff .  # This will check and show changes made by isort

      - name: Run smoke tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest tests/smoke_tests
