name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy isort python-dotenv pytest openai==0.28.0 twilio==8.11.0

      - name: Set up environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "ACCOUNT_SID=${{ secrets.ACCOUNT_SID }}" >> .env
          echo "AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}" >> .env
          echo "TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }}" >> .env
          echo "CAREGIVER_PHONE_NUMBER=${{ secrets.CAREGIVER_PHONE_NUMBER }}" >> .env
          echo "CAREGIVER_DESCRIPTION=${{ secrets.CAREGIVER_DESCRIPTION }}" >> .env
          echo "RESIDENT_FIRST_NAME=${{ secrets.RESIDENT_FIRST_NAME }}" >> .env
          echo "RESIDENT_LAST_NAME=${{ secrets.RESIDENT_LAST_NAME }}" >> .env
          echo "RESIDENT_AGE_YEARS=${{ secrets.RESIDENT_AGE_YEARS }}" >> .env
          echo "RESIDENT_SEX=${{ secrets.RESIDENT_SEX }}" >> .env
          echo "RESIDENT_MEDICAL_CONDITIONS=${{ secrets.RESIDENT_MEDICAL_CONDITIONS }}" >> .env

          echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

#      - name: Run Flake8
#        run: |
#          flake8 --ignore=W293,W503 .
#
#      - name: Run MyPy
#        run: |
#          mypy --ignore-missing-imports .

#      - name: Automatically fix import order with isort
#        run: |
#          isort .
#
#      - name: Commit and push if changes
#        run: |
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git add -A
#          git commit -m "Automatically fix Python import order" || echo "No changes to commit"
#          git push origin main || echo "No changes to push"

      - name: Run smoke tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          cd tests/smoke_tests
          pytest test_smoke.py

      - name: Run Unit tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          cd tests/unit_tests
          pytest test_unit.py

      - name: Run integration tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          cd tests/integration_tests
          pytest test_gpt_prompts.py