name: Main Workflow

on:
  push:
    branches:
      - main  # Run linting when making changes to main
  pull_request:
    branches:
      - main  # Run linting when making pull request to main

jobs:
  run_all_workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Run Lint
        uses: ./.github/workflows/Lint.yml
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Smoke Tests
        uses: ./.github/workflows/SmokeTests.yml
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}